---
title: 'MATH 4025: Missing Data'
---

```{python}
#| include: false

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer, KNNImputer
from plotnine import *
from itables import show
import warnings
import missingno as msno

warnings.filterwarnings('ignore')
np.random.seed(4025)

ames = pd.read_csv("../data/ameshousing_missing.csv")
```

## Concept Check

- Define the following types of bias (you may have to google):
    + Selection bias
    + Survivorship bias
    + Non-response bias
    + Response bias
    + Social desirability bias


# Missing Data

## Missing Data

-   This lecture we will primarily focus on missing **values** (i.e. we have observations that don't have values for one or more variables)
-   Also (maybe more) important: missing data is not necessarily the same as having a missing value... 
-   Ask yourself: Is my sample representative of the population I'm going to be applying the model to?
-   You could have observations which are not in your data set which create bias in your sample (Garbage in, Garbage out)

## Missing values {.smaller}

-   Many times, you can't just drop missing values
-   Even if you can, dropping observations with missing values can generate *biased* data/models
-   Sometimes missing values give you more information
-   MOST IMPORTANT TAKEAWAY: that data is missing in the first place, may be informative
-   Types of missing data:
    +   Missing completely at random (MCAR): there is no pattern to your missing values
    +   Missing at random (MAR): missing values are dependent on other values in the data set
    +   Missing not at random (MNAR): missing values are dependent on the value that is missing
-   Structured missingness (SM):  when the missingness of certain values are depends on one another, regardless of whether the missing values are MCAR, MAR, or MNAR


## MCAR: Examples

-   Sensor data: occasionally sensors break so you're missing data randomly
-   Survey data: sometimes people just randomly skip questions
-   Survey data: customers are randomly given 5 questions from a bank of 100 questions

## MAR: Examples

-   Men are less likely to respond to surveys about depression
-   Medical study: patients who miss follow-up appointments are more likely to be young
-   Survey responses: ESL respondents may be more likely to skip certain questions that are difficult to interpret (only MAR if you know they are ESL)
-   Measure of student performance: students who score lower are more likely to skip questions

## MNAR: Examples

-   Survey on income: respondent may be less likely to report their income if they are poor
-   Survey about political beliefs: respondent may be more likely to skip questions when their answer is perceived as undesirable
-   Customer satisfaction: only customers who feel strongly respond
-   Medical study: patients refuse to report unhealthy habits

## Structurally Missing: Examples

-   Health survey: all questions related to pregnancy are left blank by males
-   Bank data set: combination of home, auto, and credit cards... not all customer have all three so have missing data in certain portions
-   Survey: many respondents may stop the survey early so all questions after a certain point are missing
-   Netflix: customers may only watch similar movies and TV shows

## Remedies for Missing Data

-   Lot of complicated ways that you can read about
-   Can drop column if too much of the data is missing
-   Imputing with `scikit-learn`:
    +  `SimpleImputer(strategy='median')`: used for numeric (especially discrete) variables
    +  `SimpleImputer(strategy='mean')`: used for numeric variables
    +  `SimpleImputer(strategy='most_frequent')`: used for nominal (having no order) categorical variable
    +  `KNNImputer()`: used for both numeric and categorical variables (computationally expensive)
-   Treat missingness as a feature [more info](https://scikit-learn.org/stable/modules/impute.html#marking-imputed-values)
    
## Exploring Missing Data

[Use `missingno` package](https://github.com/ResidentMario/missingno)

Let's practice on the (new) ames housing dataset.

## Missing Data: Garage_Type

-   The reason that `Garage_Type` is missing is because there is no garage!
    +   Solution: replace `NaN`s with `No_Garage` (use `df.fillna()`)
    +   Do this before data splitting
    

## Missing Data: Year_Built

-   Typically MCAR (if artificially removed) or MNAR 
    +   Solution 1: Impute with mean or median
    +   Solution 2: Impute with KNN... maybe we can infer what the values are based on other values in the data set?
    
## Imputing `Year_Built`

Let's try three different imputers, KNN, mean, and median.

## Recap {.smaller}

- **Missing Data**: Not all missing data is created equal. Be aware of MCAR, MAR, MNAR, and Structural Missingness.
- **Consequences**: Dropping missing data without consideration can bias your model and result in the loss of useful information.
- **Remedies**:
    + Simple imputation (mean, median, mode) using `SimpleImputer`.
    + Advanced imputation (e.g. using `KNNImputer`) leveraging patterns in your data.
    + Domain logic: e.g., missing Garage means "No Garage".
- **Implementation**: Chain imputers with scalers using `scikit-learn`'s `Pipeline` to efficiently and safely handle missing data.
