---
title: 'MATH 4025: Visualizing Classification Trees'
---


## Exploring Decision Trees with App {.smaller}

-   Dr. F will split you into four groups
-   On one of your computers connect to a TV and [open this app](https://efriedlander.shinyapps.io/ClassificationMetrics/)
-   Do the following based on your group number:
    +   1: Choose **plane** on the first screen
    +   2: Choose **circle** on the first screen
    +   3: Choose **parabola** on the first screen
    +   4: Choose **sine curve** on the first screen
-   We will generate data from this population... do you think KNN, logistic regression, or a decision tree will yield a better classifier? Why?

## Exploring Decision Trees with App {.smaller}

-   Choose one of the populations
-   Generate some data
-   Fit a decision tree to the data and see how the different hyperparameters impact the resulting model:
    +   **Complexity parameter (cp)**: the larger the number, the more pruning
    +   **Minimum leaf size**: minimum number of training observations that must be in a leaf
    +   **Max depth**: maximum number of splits before a terminal node
-   Write down any interesting observations