---
title: "Homework 1: Exploratory Data Analysis"
---

Adapted from "Start teaching with R," created by R Pruim, N J Horton, and D Kaplan, 2013, "Interactive and Dynamic Graphics for Data Analysis," by Dianne Cook and Deborah F. Swayne, Colby Long's DATA 325 Course at Wooster College and Maria Tackett's STA-210 course at Duke University.

# Introduction

In this homework we will familiarize ourselves with the tools that we'll use throughout the course and refresh ourselves on topics related to exploratory data analysis.

## Course Toolkit

The primary tools we'll be using in this course are **Python**, **Positron**, **git**, and **GitHub**. We will be using them throughout the course both to learn the concepts discussed in the course and to analyze real data and come to informed conclusions.

::: callout-note
**Python** is the programming language. **Positron** is the Integrated Development Environment (IDE) where we write code. **Miniforge/Conda** manages our Python installations and packages.
:::

::: callout-note
**Git** is a version control system (like "Track Changes" but for code) and **GitHub** is the cloud hosting service for your Git projects.
:::

To make versioning simpler, this homework will be completed individually. In the future, you'll learn about collaborating on GitHub.

## Exploratory Data Analysis

One of the most important components of data science is exploratory data analysis. I really like the following definition, which comes from [this article](https://towardsdatascience.com/exploratory-data-analysis-8fc1cb20fd15) (though it's probably not the original source).

> Exploratory Data Analysis refers to the critical process of performing initial investigations on data so as to discover patterns, spot anomalies, to test hypotheses and to check assumptions with the help of summary statistics and graphical representations.

Before you begin your exploratory analysis, you may already have a particular question in mind. For example, you might work for an online retailer and want to develop a model to predict which purchased items will be returned. Or, you may not have a particular question in mind. Instead, you might just be asked to look at browsing data for several customers and figure out some way to increase purchases. In either case, before you construct a fancy model, you need to explore and understand your data. This is how you gain new insights and determine if an idea is worth pursuing.

## Learning goals

By the end of the homework, you will...

-   Be familiar with the workflow using Python and GitHub
-   Gain practice writing a reproducible report using Jupyter notebooks
-   Practice version control using GitHub and Conda/Mamba
-   Be able to create numerical and visual summaries of data
-   Use those summaries

# Getting Started

## Setting Up Your Environment

Before we analyze data, we need to set up our computer. This process involves installing a package manager (Miniforge), creating a virtual environment, and installing the necessary libraries.

### Install Miniforge

We will use **Miniforge** to manage our Python installation. It pre-configures `conda` (package manager) and `mamba` (a faster version of conda) with the `conda-forge` channel, which is the community standard.

1.  Go to the [Miniforge GitHub page](https://github.com/conda-forge/miniforge).
2.  Download the **Miniforge3** installer for your operating system (Windows, macOS, or Linux).
3.  Run the installer and follow the prompts.
    *   *Windows*: Open "Miniforge Prompt" after installation to verify.
    *   *Mac/Linux*: Open your terminal.
4.  If you're on Mac or Linux run the following in your terminal if you're on Windows write it in the provided **Miniforge Prompt**:
    * `conda config --set auto_activate_base false`

### Create a Conda Environment
We never want to install packages into our "base" environment. Instead, we create a specific environment for this course. Open your terminal (or Miniforge Prompt) and run:

```bash
mamba create -n math4025 python=3.14
```
*   `mamba create`: Command to create an environment.
*   `-n math4025`: Names the environment "math4025".
*   `python=3.14`: Specifies the Python version.

### Activate the Environment
To use the environment, you must activate it:

```bash
mamba activate math4025
```
You should see `(math4025)` appear in your prompt.

### Install Packages
Now we install the tools we need for this assignment.

```bash
mamba install pandas numpy seaborn matplotlib plotnine jupyter
```
*   `pandas`, `numpy`: Data manipulation.
*   `seaborn`, `matplotlib`, `plotnine`: Data visualization.
*   `jupyter`: Required to run Notebooks.

In the future, any time you want to install a package:

- Make sure your `math4025` environment is activated
- Install it using `mamba install name-of-package`

## Setting up Positron & Git

If you've already set up Positron and Git in a previous course, you can skip this section.

### Install Positron
We will use **Positron**, a new data science IDE from Posit (makers of RStudio).

1.  Download and install [Positron](https://positron.posit.co/install.html).
2.  Open Positron.
3.  Select your Python Interpreter:
    *   Open the Command Palette (`Ctrl+Shift+P` or `Cmd+Shift+P`).
    *   Type `Python: Select Interpreter`.
    *   Choose the `math4025` environment you just created.

### Configure Git & GitHub

You need a **Personal Access Token (PAT)** to allow Positron to talk to GitHub securely.

1.  Log in to [GitHub](https://github.com/).
2.  Go to **Settings** > **Developer settings** > **Personal access tokens** > **Tokens (classic)**.
3.  **Generate new token (classic)**.
4.  Name it "Math4025", select the **`repo`** scope, and generate.
5.  **Copy the token immediately!**
6.  Configure Git on your machine (run in terminal):
```bash
git config --global user.name "Your Github Username"
git config --global user.email "your.email@example.com"
```
7.  When asked for a password during cloning/pushing, paste your **PAT**.

# The Assignment

Now you will create your own Jupyter Notebook to analyze tipping data.

### Clone the Repository

1.  Go to the course [GitHub assignment](https://classroom.github.com/a/lqxGMOZJ).
2.  Copy the URL.
3.  In Positron: `Control Palette` > `Git: Clone` > Paste URL.
4.  When deciding where to save the work from this class:
    -  **DON'T STORE YOUR WORK IN A FOLDER THE AUTOMATICALLY SYNCS WITH ONEDRIVE, DROPBOX, ETC.**
    -  I recommend creating a folder on your computer dedicated to this class
    -  Make each assignment a sub-folder in this folder.

### Create Your Notebook

1.  In Positron, create a new file named `hw01-analysis.ipynb` inside your repository folder.
2.  In the top right corner of the notebook you should see a button that says "Select Kernel". Click that button, you should see an option for the mamba environment that you've created. You should always use this one.
3.  In Jupyter notebooks, there are two different types of cells: 
    -   **markdown** cells that allow you to write markdown. This is where you will write all of your prose and interpretation. [Here is a good markdown cheatsheet](https://www.markdownguide.org/cheat-sheet/).
    -   **code** cells that allow you to write python code.  Be careful when you are running your code cells. If you run them out of order, notebook may not work that way you want when a new person runs the whole notebook in order.
4.  Add a Markdown cell at the top with a title "Homework 1: Exploratory Data Analysis" and your name. You can use \# symbols to create headings. The more you add the smaller the heading will be.


## Understand Your Data

Today we will be working with the `TIPS` data set which is in the `regclass` R package. I've saved the data as a csv and included it in the repo for this assignment. The data in the `TIPS` dataset is information recorded by one waiter about each tip he received over a period of a few months working in a restaurant. We would like to use this data to address the question, *"What factors affect tipping behavior?"*

### Loading packages in `Python`

We will need to leverage several different python packages to analyze our data.In python you can `import` packages in a few ways. Consider the following ways of importing the `pandas` package, which is the primary package we will use to manipulate data:

- `import pandas` will import pandas. Every time you want to use a pandas function you'll have to prepend `pandas.` (e.g. `pandas.read_csv()`)
- `import pandas as pd` will import pandas and allow you to use the shorthand `pd` (e.g. `pd.read_csv()`)
- `from pandas import *` will import every function from pandas (e.g. `read_csv()`). In general, it's not a good idea to do this as you may create unintended conflicts if multiple packages have functions with the same name.
- `from pandas import read_csv()` will import only `read_csv()` (e.g. `read_csv()` will work but no other `pandas` functions will work)

Common conventions in data science:

```{python}
#| eval: false
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from plotnint import *
# OR
import plotnine as p9
```

### Exercise 1

::: {.callout-tip title="Task"}
In your Jupyter notebook, create a code cell at the top and load `pandas`. When you need to load a new package, I recommend returning to this cell and importing it here rather that in the first cell that you need it. 

After you've loaded `pandas` create a new markdown cell where you describe the goal of the notebook and the data. Do not write any code, but I suggest referencing [the documentation](https://cran.r-project.org/web/packages/regclass/regclass.pdf) for this data set and writing down any relevant details. Finally, create a new code cell and load the tips data using `pd.read_csv()`.
:::

## Using git to track your changes

There are two ways to do this. You can either do this from the **Source Control** extension for Positron or from the command line (I've outlined both below). While the Positron extension is perfectly acceptable for this class, it is probably a good idea to learn to use the command line at some point if your plan it to do more data science.

### Using Source Control Extension

Click onthe Source Control extension in the left-hand panel.

#### Staging your changes

Before we move on ensure that you DO NOT COMMIT YOUR CHANGES WITHOUT A COMMIT MESSAGE. This will make sense in a minute, but if you see a button that says "Commit", don't click it until you've finished reading this section.

If you have made changes to your files, you should see it listed here. Clicking on these files shows you the difference between the last committed state of the document and its current state, including changes. You should see deletions in red and additions in green.

If you're happy with these changes, we'll prepare the changes to be pushed to your remote repository. Stage your changes by clicking the `+` button next to the file you want to stage. When you do this you are preparing to save these changes to your version history.

#### Committing changes

When you *commit* changes, you add the changes you've staged to the version history of your repository.
Write a meaningful commit message (for instance, "update author name") in the Commit message box. Finally, click Commit. Note that every commit needs to have a commit message associated with it. **DO NOT CLICK COMMIT WITHOUT WRITING A COMMIT MESSAGE**.

You don't have to commit after every change, as this would get quite tedious. You should commit states that are meaningful to you for inspection, comparison, or restoration.

In the first few assignments I will nudge you when to commit and in some cases, what commit message to use. As the semester progresses we will let you make these decisions.

#### Pushing changes

Go to your GitHub repo and refresh the page. Uh oh! You probably don't see that changes you've made yet. This is because you still need to *push* your changes to Github. There are a few ways to do this, if you're new to Git raise your hand.


#### Using the Command Line

Eventually you'll be better off using git from the terminal or command line:

- `git add files-you-want-to-stage` or `git add .` to stage all files that have changed
- `git commit -m "This is your commit message"`
- `git push` to push your changes
- `git pull` to pull changes from your remote repo


### Exercise 2

When exploring a new data set, it’s important to first understand the basics. What format is our data in? What types of information are included in the data set? How many observations are there?

In the Python ecosystem, data sets are usually stored in a 2-dimensional structure called a **DataFrame**. The `pandas` library has long been the industry standard for data manipulation. You can find more the documentation [here](https://pandas.pydata.org/docs/index.html) and a quick tutorial can be found [here](https://pandas.pydata.org/docs/user_guide/10min.html). If you're coming from R, you may find [this webpage](https://pandas.pydata.org/docs/getting_started/comparison/comparison_with_r.html#compare-with-r) helpful (I've bookmarked it). Suppose you've loaded a dataset using `pd.read_csv()` and called it `df`. After importing this `pandas` (which you've done), you can get an idea of the structure of a data set using `df.info()`, and you can peek at the first few rows with `df.head()`. If you're used to using R, one thing you'll notice that all of these data manipulations are *methods* rather than functions. Create a code chunk and use these functions (and others) to better understand the data. Use `tips.head()`, `tips.info()`, or `tips.describe()` to explore the dataset. 

::: {.callout-tip title="Task"}
Use the above functions to determin the number of tips recorded in this data set? Ensure it matches the description of the data from the documentation.
:::

### Exercise 3

Often, a data set will come with a *code book* which gives more complete information about the structure of the data, the meaning of variables, and how the data were collected. You can find descriptions for this data in the documentation linked above.

::: {.callout-tip title="Task"}
Even though the column names are self-explanatory, we might have more questions about the data. For example, we might conjecture that people tip differently for breakfast and lunch, but our data only tells us if the bill was paid at "Day" or "Night." State another reasonable conjecture about a factor that might affect tipping behavior. What additional information would be helpful to explore that conjecture? Do not write any code.
:::

::: {.callout-warning title="Render-Commit-Push"}
This is a good place to render, commit, and push changes to your GitHub repo. Write an informative commit message (e.g. "Complete exercises 1 - 3"), and push every file to GitHub.
:::

# Numerical Summaries

Now we'd like to start looking closely at the data set to develop some ideas about what factors might affect tipping. In **pandas**, basic descriptive statistics have intuitive names like `mean()`, `median()`, `std()`, and `quantile()`. When exploring your data, you typically use these methods directly on a DataFrame or Series, often in conjunction with `agg()` (similar to `summarize` in the tidyverse) to compute multiple statistics at once. We can apply these functions to an entire DataFrame or isolate a specific column using bracket notation.


### Exercise 4

::: {.callout-tip title="Task"}
Use some of these summaries to answer the following. How many smokers are in the data set? How fancy do you think this restaurant is? Is it possible to tell from this summary how many different shifts the waiter worked? Why or why not?

Before we try to write any code, **write down the operations you want to do to get the answers**. For example, *count the number of rows in which the `Smoker` column has `Yes`*. Then translate those into code.
:::

### Exercise 5


As we start to explore different questions, we might want to know things about interactions between variables. Like, are tips larger during the day or at night? Or does gender or smoking status matter for how much people spend and how much they tip? In **pandas**, you can calculate statistics within groups using the `groupby` method followed by an aggregation function.

::: {.callout-tip title="Task"}
Calculate the variance of the tip percentage broken down by day of the week. Do you notice anything unusual? Explore the data and determine a possible cause for this.
:::

::: {.callout-warning title="Render-Commit-Push"}
This is a good place to render, commit, and push changes to your hw-eda repo on GitHub. Write an informative commit message (e.g. "Complete exercises 2 - 5"), and push every file to GitHub by clicking the checkbox next to each file in the Git pane. After you push the changes, the Git pane in RStudio should be empty.
:::

# Graphical Summaries

Graphical summaries are a key tool in exploratory data analysis to to help you understand your data. They also help you communicate insights about your data to others. For example, we might want to display relationships about some of our categorical variables. So we could start by graphing different party sizes in our data set. In general, graphical summaries are preferable to numerical summaries. The human brain is better at recognizing visual patterns than it is in parsing numbers.

There are a few different packages for generating plots in Python:

- [`matplotlib`](https://matplotlib.org/): The foundational "grandfather" of Python plotting, offering granular low-level control for creating static, publication-quality figures, though often requiring verbose code.
- [`seaborn`](https://seaborn.pydata.org/): A high-level wrapper built on `matplotlib` that simplifies statistical visualization (like heatmaps and regression plots) with beautiful default themes and fewer lines of code.
- [`plotnine`](https://plotnine.org/): A strict implementation of the "Grammar of Graphics" (mimicking R's `ggplot2`), designed for users who prefer building plots by logically layering data, aesthetics, and geometries.
- [`plotly`](https://plotly.com/): The best choice for **interactive** and web-ready charts, allowing users to zoom, pan, and hover over data points, making it ideal for dashboards.


### Exercise 6

::: {.callout-tip title="Task"}
Create the following plots using the library of your choice (I recommend against `plotly`) unless you already know how to use it). Remember that you will need to import the packages.

*   **Plot 1**: A bar chart of `sex`.
*   **Plot 2**: A histogram of `total_bill`.
*   **Plot 3**: A scatterplot of `total_bill` vs `tip`, colored by `smoker`.
:::


## Bivariate Plots

We may also be interested in comparing variables. To do so we should consider the following scenarios:

- Categorical vs. categorical: your best bet is some kind of bar chart. If you're interested in showing proportions or rates, use a standardized bar chart, if not, use a stacked bar chart or a dodged bar chart.
- Categorical vs. numerical: there are many options here. Simplest would be boxplots, but this can often obscure information. Better plots would be boxplots with a jitter plot overlay, sina plots, or violin plots. See the code below for how to implement these is `matplotlib`, `seaborn`, and `plotnine`.
- Numerical vs. Numerical: a good ole-fashioned scatter plot.

#### `matplotlib`

`matplotlib` offloads a lot of the data prepartion to you so you'll usually have to do some processing using `pandas`.

```{python}
#| eval: false

# Prepare data: Create a list of 'Tip' arrays, one for each 'Weekday'
days = tips['Weekday'].unique()
data_by_day = [tips[tips['Weekday'] == d]['Tip'] for d in days]

# --- Plot 1: Boxplot ---
plt.boxplot(data_by_day, tick_labels=days)
plt.title("Tips by Day of the Week")
plt.xlabel("Day of the Week")
plt.ylabel("Tips")

# --- Plot 2: Boxplot + Jitter ---
plt.boxplot(data_by_day, tick_labels=days)
# Doesn't have jitter plot so must add jitter manually
for i, d in enumerate(days):
    y = tips[tips['Weekday'] == d]['Tip']
    x = np.random.normal(i + 1, 0.04, size=len(y)) # i+1 because boxplot is 1-indexed
    plt.scatter(x, y)
plt.title("Tips by Day of the Week")
plt.xlabel("Day of the Week")
plt.ylabel("Tips")

# --- Plot 3: Violin ---
plt.violinplot(data_by_day, showmeans=False, showmedians=True)
plt.xticks(ticks=range(1, len(days) + 1), labels=days)
plt.title("Tips by Day of the Week")
plt.xlabel("Day of the Week")
plt.ylabel("Tips")

# --- Plot 4: Sina Plot Approximation ---
# Matplotlib has no native Sina plot. 
# A common approximation is a Violin plot with inner points (or a swarm plot).
# Here we just show the violin (density) with scatter overlay.
parts = plt.violinplot(data_by_day)
for pc in parts['bodies']:
    pc.set_facecolor('#D43F3A')
    pc.set_alpha(0.3)
for i, d in enumerate(days):
    y = tips[tips['Weekday'] == d]['Tip']
    x = np.random.normal(i + 1, 0.04, size=len(y))
    plt.scatter(x, y, alpha=0.6, s=10)
plt.xticks(ticks=range(1, len(days) + 1), labels=days)
plt.title("Tips by Day of the Week")
plt.xlabel("Day of the Week")
plt.ylabel("Tips")
```

#### `seaborn`

`seaborn` codee looks a lot like `matplotlib` but takes care of most of the processing for you. However, `seaborn` tends to be a slow package. 

```{python}
#| eval: false

# --- Plot 1: Boxplot ---
sns.boxplot(data=tips, x='Weekday', y='Tip')
plt.title("Tips by Day of the Week")

# --- Plot 2: Boxplot + Jitter ---
sns.boxplot(data=tips, x='Weekday', y='Tip', fliersize=0) # Hide outliers
sns.stripplot(data=tips, x='Weekday', y='Tip', jitter=True, color='black', alpha=0.5)
plt.title("Tips by Day of the Week")

# --- Plot 3: Violin ---
sns.violinplot(data=tips, x='Weekday', y='Tip')
plt.title("Tips by Day of the Week")

# --- Plot 4: Sina Equivalent (Swarmplot or Violin+Strip) ---
# Seaborn uses 'swarmplot' for non-overlapping points (beeswarm style)
sns.violinplot(data=tips, x='Weekday', y='Tip', inner=None, color=".8")
sns.stripplot(data=tips, x='Weekday', y='Tip', jitter=True)
plt.title("Tips by Day of the Week")
```

#### `plotnine`

`plotnine` mimicks `ggplot2` syntax (mostly). Note that you'll have to wrap your plots in parenthesis because Python can't follow the line breaks in the same way as R. In addition, if you want to create multiple plots in the same cell, you have two options. One option is to convert your `plotnine` plots into `matplotlib` objects using the `.draw()` method to convert a `plotnine` object into a `matplotlib` figure or `._draw_using_figure(fig, [ax])` to assign the `plotnine` object to an existing axis within a `matplotlib` figure. The second is to use `brick` from the package [`patchworklib`](https://github.com/ponnhide/patchworklib) which allows you to arrange figures.

```{python}
#| eval: false
# --- Plot 1: Boxplot ---
(
    ggplot(tips, aes(x='Weekday', y='Tip'))
    + geom_boxplot()
    + labs(title="Tips by Day of the Week", x="Day of the Week", y="Tips")
)

# --- Plot 2: BoxpFlot + Jitter ---
(
    ggplot(tips, aes(x='Weekday', y='Tip'))
    + geom_boxplot(outlier_shape=None) # Hide outliers so they aren't plotted twice
    + geom_jitter(width=0.2)
    + labs(title="Tips by Day of the Week", x="Day of the Week", y="Tips")
)

# --- Plot 3: Violin ---
(
    ggplot(tips, aes(x='Weekday', y='Tip'))
    + geom_violin()
    + labs(title="Tips by Day of the Week", x="Day of the Week", y="Tips")
)

# --- Plot 4: Sina ---
(
    ggplot(tips, aes(x='Weekday', y='Tip'))
    + geom_sina()
    + labs(title="Tips by Day of the Week", x="Day of the Week", y="Tips")
)
```

### Pairplots

Look at the documentation for `seaborn`'s [`pairplot`](https://seaborn.pydata.org/generated/seaborn.pairplot.html) and [`PairGrid`](https://seaborn.pydata.org/generated/seaborn.PairGrid.html).

::: {.callout-warning title="Render-Commit-Push"}
This is a good place to render, commit, and push changes to your GitHub repo. Write an informative commit message (e.g. "Complete exercises 1 - 3"), and push every file to GitHub.
:::


### Exercise 7

::: {.callout-tip title="Task"}
Create the following charts.

- Bar chart of `PartySize`
- A stacked bar chart of `Weekday` broken down by `Smoker`
- A standardized bar chart of `Weekday` broken down by `Smoker`
- A histogram of `Tip` using 100 bins
- A plot of `Tip` vs. `Smoker`
- At least one scatter plot
:::

### Exercise 8

::: {.callout-tip title="Task"}
Use your new found skills to figure out which day of the week has the highest *percentage* of tables that are smokers? Hint: look at documentation and use Google to figure out how to create proportions.
:::

### Exercise 9

::: {.callout-tip title="Task"}
Notice that there are a few "spikes" in the histogram above. What do you think is causing this?
:::

::: {.callout-warning title="Render-Commit-Push"}
This is a good place to render, commit, and push changes to your GitHub repo. Write an informative commit message (e.g. "Completed exercise 6-9"), and push every file to GitHub.
:::


## Exercise 10

::: {.callout-tip title="Task"}
Using the skills you learned above. Conduct a thorough exploration of the question *What factors effect tipping behavior?*. Be prepared to present your exploration in class on Thursday. You can present directly from your Jupyter notebook. For your exploration to be complete the following conditions must be met:

1. An observer should have no additional questions about the data.
2. You should avoid displaying any unnecessary information.
:::

::: {.callout-warning title="Render-Commit-Push"}
This is a good place to render, commit, and push changes to your GitHub repo. Write an informative commit message (e.g. "Completed exercises assignment"), and push every file to GitHub.
:::

::: callout-caution
Before you're done with you work, make sure you look it over one last time to make sure the rendered document looks like you want it to! I recommend re-running the notebook from the top. I can't tell you how often students turn in work and their output doesn't match their prose or the output definitely doesn't look the way they wanted it to.
:::
