---
title: "Homework 3: $K$-Nearest Neighbors"
---

```{python setup}
#| include: false

# load packages here
```

# Introduction

In this homework, you will practice applying the $K$-Nearest Neighbors (KNN) method which is capable of performing both classification and regression.

## Learning goals

By the end of the homework, you will...

-   Fit and interpret KNN models in both regression and classification settings
-   Compare and evaluate different KNN models

# Getting Started

## Clone the repo
The following directions will guide you through the process of setting up your homework.

## Exercise 0

::: {.callout-tip title="Question"}
[Click this link](https://classroom.github.com/a/RJ9siXnp) to accept the assignment and clone it to your computer.
:::

# $K$-Nearest Neighbors

The basic idea is that predictions are made based on the $K$ observation in the training data which are "closest" to the observation that we're making a prediction for. While many different **metrics** (i.e. measures of distance) can be used, we will work exclusively with the **Euclidean metric**: $$\text{dist}(x, y) = \sqrt{\sum_{i=1}^p(x_i-y_i)^2}$$ for vectors $x = (x_1,\ldots, x_p)$ and $y = (y_1,\ldots,y_p)$.


# KNN for Regression

For regression, we can predict the response variable for our point to be the average (or sometimes median) of the response variable for the $K$-nearest neighbors.

## Data & Dummy Variables

For this portion of the homework, we'll use the `Carseats` data from the `ISLP` package (accessible using `load_data('Carseats')`). Frequently, when working with categorical data, you will be required to transform that data into **dummy variables**. Namely, you'll create a unique variable for each column which gets a 1 if the corresponding observation is from that category and a 0 otherwise. In data science, this format is sometimes referred to as **one-hot encoding**.

## Exercise 1

::: {.callout-tip title="Question"}
Look at the `Carseats` data from the `ISLP` package. Then, split the data into a training and test set using a 70-30 split and a seed of 4025 (as usual).
:::

## Exercise 2

::: {.callout-tip title="Question"}
Look at your data. What transformation are necessary before we apply KNN? Why?
:::

## Exercise 3

::: {.callout-tip title="Question"}
DO NOT WRITE ANY CODE UNTIL THE NEXT EXERCISE. Your goal is to create a KNN model that best predicts `Sales`. In your group, decide on a strategy for finding the best set of features and number of neighbors to include in your model. How will you take care of preprocessing?What metrics will you use to determine which model is "best"? What data will you use to make your decision? What models will you fit and evaluate? How will you visualize your results? Once you've sketched out your strategy, get approval from Dr. F.
:::

## Exercise 4

::: {.callout-tip title="Question"}
After getting approval from Dr. F implement the strategy you agreed on. You should be prepared to present your strategy and results to the class.
:::

## KNN for Classification

We'll start by using KNN for classification.

## Data

We will be working with the famous `iris` data set which consists of four measurements (in centimeters) for 150 plants belonging to three species of iris. This data set was first published in a classic 1936 paper by English statistician, and notable racist/eugenicist, Ronald Fisher. In that paper, multivariate linear models were applied to classify these plants. Of course, back then, model fitting was an extremely laborious process that was done without the aid of calculators or statistical software. **For now, don't worry about centering and scaling your data until Exercise 9.**

## Exercise 5

::: {.callout-tip title="Question"}
Import the `sklearn.datasets` package (or `seaborn` or `ISLP`), take a look at the columns of `iris`, and split your data into training and test sets using a 70-30 split. IMPORTANT: Make sure that each species is represented proportionally in the training set by using the `stratify` argument in the `train_test_split` function! Once again, set your `random_state` to 4025. Explain what `stratify` does and why it is important in this case.
:::

## Exercise 6

::: {.callout-tip title="Question"}
Create a scatter plot of your training set with `sepal width` and `petal width` on the x- and y- axes, respectively, and color the points by species (the names may vary depending on how you loaded the data).
:::

## Exercise 7

::: {.callout-tip title="Question"}
As the name suggests, the $K$-nearest neighbors (KNN) method classifies a point based on the classification of the observations in the training set that are nearest to that point. If $k > 1$, then the neighbors essentially "vote" on the classification of the point. Using only your graph, if $k = 1$, how would KNN classify a flower that had sepal width 3cm and petal width 1cm?
:::

## Exercise 8

::: {.callout-tip title="Question"}
Just to verify that we are correct, find the sepal width, petal width, and species of the observation in your training set that is closest to our flower with sepal width 3cm and petal width 1cm. This should be done by computing the Euclidean distance of (3, 1) to each observation and then sorting the resulting DataFrame to get the row with the smallest distance.
:::

## Exercise 9

::: {.callout-tip title="Question"}
We really shouldn't use the raw data as is when buildling our model. Looking at your data, what transformations will you need to perform before fitting your data. Why?
:::

## Exercise 10

::: {.callout-tip title="Question"}
Create a `Pipeline` to fit a KNN model with 1 neighbor that includes the transormation(s) above and fit the model to your training set.
:::

We would like to understand how the method of $K$-nearest neighbors will classify points in the plane. That is, we would like to view the *decision boundaries* of this model. To do this, we will use our model to classify a large grid of points in the plane, and color them by their classification. The code below creates a DataFrame called `grid` consisting of 62,500 points in the plane.

```{python}
#| eval: false

xx, yy = np.meshgrid(np.linspace(2.0, 4.5, 250), 
                     np.linspace(0.0, 2.5, 250))
grid = pd.DataFrame({'sepal_width': xx.ravel(), 
                     'petal_width': yy.ravel()})
```

## Exercise 11

::: {.callout-tip title="Question"}
Use the code above, and change the variable names so that it will work with your model. Classify the points in `grid` using your training data and $k = 1$. Then, plot the points in `grid` colored by their classification. Make sure your code is written so that the grid points are being centered and scaled before predictions are being made for them.
:::

## Exercise 12

::: {.callout-tip title="Question"}
Notice that the decision boundary between `versicolor` and `virginica` looks a little strange. What do you observe? Why do you think this is happening? Does using $k = 2$ make things better or worse? Why do you think that is?
:::

## Exercise 13

::: {.callout-tip title="Question"}
Determine which value of $k$, the number of neighbors selected, gives the highest accuracy on the test set. Test all $k$s between 1 and 40. Note that there may be ties because our data set is a little bit too small. To break ties just choose the smallest $k$ among the ones which are tied. Hint: A for-loop may be helpful. What is the accuracy of the model you ended up choosing?
:::

Awesome!! Your model probably did pretty well because KNN performs really well on the `iris` data set. However, this isn't a very challenging data set for most classification methods. More challenging data sets have data on different scales and *class imbalance* where there are very few observations belonging to a particular class.
