---
title: "Homework 9: Boosting and Multiclass Classification"
author: "Your Name"
---

# Introduction

In this homework, we will practice solving multi-class classification problems using gradient boosted trees.

## Learning goals

In this assignment, you will...

-   Fit gradient boosted trees
-   Use variable importance plots to interpret your model
-   Interpret multi-class classification metrics

# Getting Started

 The GitHub assignment can be found [here](GITHUB_CLASSROOM_LINK). Rules:

## Data: `academic_success`

We will be using a data set from the UCI Machine Learning Repository. From the website:

> A dataset created from a higher education institution (acquired from several disjoint databases) related to students enrolled in different undergraduate degrees, such as agronomy, design, education, nursing, journalism, management, social service, and technologies. The dataset includes information known at the time of student enrollment (academic path, demographics, and social-economic factors) and the students' academic performance at the end of the first and second semesters. The data is used to build classification models to predict students' dropout and academic success. The problem is formulated as a three category classification task, in which there is a strong imbalance towards one of the classes.

Our goal will be to predict the column `Target` which contains three different factors:

-   `Dropout`: the student dropped out before graduating
-   `Enrolled`: the student graduated but took extra time
-   `Graduate`: the student graduated on time

More information (such as feature descriptions) can be found on the [website here](https://archive.ics.uci.edu/dataset/697/predict+students+dropout+and+academic+success).

# Exploratory Data Analysis

## Exercise 1

::: {.callout-tip title="Question"}
Load the data set. You can either download the data from that page and place the CSV file in your repo's `data/` folder and load it manually or you can import directly by clicking the "IMPORT IN PYTHON" button on the website and following the directions. Note that the file is delimited by semicolons (`;`) instead of commas. After loading, clean up the column names (e.g., convert to lowercase and replace spaces with underscores). Make sure to read the documentation so that you are treating the appropriate columns as categorical rather than numeric. Do any other cleaning you think is necessary.

Once that is done, split your data into training and test sets using a stratified split on the response variable.
:::

## Exercise 2

::: {.callout-tip title="Question"}
Describe the different metrics and strategies you might use to evaluate how a model performs on this data. Generate a plot of the response variable and comment on anything that you think may impact your model and these different metrics.
:::

# Pre-Processing

## Exercise 3

::: {.callout-tip title="Question"}
Generate a preprocessing pipeline using `ColumnTransformer` and `Pipeline` that can be used with a gradient boosted tree. Unlike linear models, decision trees do not require scaling. What preprocessing steps are still necessary?
:::

# Boosted Tree

## Exercise 4

::: {.callout-tip title="Question"}
Using all of the default settings in `GradientBoostingClassifier` from `sklearn.ensemble`, fit a gradient boosted tree to the training data.
:::

## Exercise 5

::: {.callout-tip title="Question"}
Compute all of the metrics you described in Exercise 2.

Our goal is to identify any student in the `Dropout` or `Enrolled` categories so that we can target interventions (e.g. extra advising, tutoring, mentorship, etc.) towards these students. It's not a big deal if students that were going to graduate on time also get these interventions because it doesn't harm students to give them some extra support they don't need. That said, the school's budget isn't infinite so we'd like to minimize the number of students who get unnecessary support, as long as the students who do need it are still getting it. Based on this goal, which metrics would you be most invested in? How does the model perform on these metrics?
:::

# Cross Validation and Parameter Tuning

## Exercise 6

::: {.callout-tip title="Question"}
Use `GridSearchCV` with `RepeatedStratifiedKFold` to tune `n_estimators` (the number of trees) and choose your best model. You may try to tune more parameters if you'd like, but this may take a long time to run. **Tip:** Use caching or save your CV results so you don't re-run cross-validation every time the document is rendered.
:::

## Exercise 7

::: {.callout-tip title="Question"}
Generate and interpret a variable importance plot. 
:::

## Exercise 8

::: {.callout-tip title="Question"}
Compute per-class (one-vs-all) metrics using `classification_report` and display a confusion matrix using `ConfusionMatrixDisplay` from `sklearn.metrics`. Interpret both in the context of the goal outlined in Exercise 5.
:::
