---
title: "Job Interview Resources"
---

As discussed at the beginning of the course, you will complete a job interview during Finals Week, worth 20% of your overall course grade. This document will guide you through preparing for it.

## Interview Preparation

::: {.callout-important}
**Key Deadline:** Your interview must be completed during Finals Week. A scheduling link will be provided closer to the end of the semester. *It is your responsibility to schedule your interview in a timely manner.*
:::

Your interview will mimic a technical interview with a hiring manager. It will last about one hour and have the following format:

1.  (5 minutes) Your interview will begin with the following two prompts:
    +   Tell me about yourself.
    +   Why are you interested in this role?
2.  (10 minutes) You will be asked questions about your resume, asking you describe the details of some of the projects or jobs you have listed. If you don't have any projects or job's that are relevant you will be asked questions about your previous coursework. In real life, it is unlikely that you'd make it to this interview without anything relevant listed on your resume.
3.  (10 minutes) You will be asked questions about the sample data analysis you turned in. For example, "Why do you choose method X instead of method Y?"
4.  (35 minutes) You will be asked general technical questions related to the role. Each of these questions will fall into one of the following categories:
    +   Questions asking you to explain something you did on your homework.
    +   Questions similar in style to those asked in Chapter 5-8 of [this book](https://huyenchip.com/ml-interviews-book/). Please note that only content that has been covered in this class, a pre-requisite for this class, or is listed on your resume will be included with a heavy focus on content from this class. 
      +   Pseudo-coding questions: E.g. "Write pseudo-code to perform gradient-descent".
      +   Theory questions: E.g. "Why do we do cross-validation?"
      +   Closed Case-Study Questions: E.g. "Suppose you are trying to build an model that classifies pictures of food as either a *hot dog* or *not a hot dog*. What metrics would you use to evaluate performance?
      +   Open-Ended Case-Study Questions: E.g. "Suppose you are tasked with building a model to predict whether an employee will leave the company within a year. How would you approach this problem?"
      
### Grading

#### Attire and Professionalism (5% of total grade)

Your attire and professionalism will account for 5% of your interview grade. The following criteria will be used to determine your grade:

-   Did the student arrive on time?
-   Did the student wear business casual attire (including dress shoes)?
    +   If you do not have business casual attire or are unclear what business casual attire is, please notify Dr. Friedlander ASAP.
-   Did the student bring a notepad and writing implement?
-   Was the student respectful?

#### Meta-cognition (5% of total grade)

The next 5% of your interview grade will be based on your meta-cognition. That is, whether you are able to self-assess what you know and what you don't know. The following criteria will be used to determine your grade:

-   Did the student seem to understand where the gaps in their knowledge were?
-   Did the student seem to know if their answers were complete?
-   Did the student think that answers that were wrong were actually right?
-   Has the student actually mastered the skills on their resume?

#### Preparation and Enthusiasm (30% of total grade)

The next 30% of your interview grade will be based on your preparation and enthusiasm. The following criteria will be used to determine your grade:

-   Did the student seem prepared to discuss their resume?
-   Did the student speak knowledgeably about their portfolio/sample analysis?
-   Did the student demonstrate knowledge of the company and role they are applying to?
-   Did the student demonstrate enthusiasm for the company and role?
-   Did the student have good questions at the end of the interview?


#### Communication (20% of total grade)

The next 20% of your interview grade will be based on your communication skills. The following criteria will be used to determine your grade:

-   Did student speak at an appropriate pace (i.e. not too fast or too slow)?
-   Did student use professional language, avoiding any slang?
-   Did student stay focused on the question being asked?
-   Were the student's answers too long or too short?
-   Were the student's answers clear?
-   Was the student good and talking through their thought process?


#### Content (40% of total grade)

The remaining 40% of your interview grade will be determined based on whether the answers to the questions asked of you are correct and complete. The following criteria will be used to determine your grade:

-   Were the student's answers correct?
-   Were the student's answers complete?
-   For open-ended questions, did the student ask for any good questions and request necessary information?
-   For open-ended questions, did the student state any assumptions they were making?

### Some General Tips

-   If you are asked a question you don't know the answer to, be honest. It is OK to say something like "I'm honestly not sure." However, unless you absolutely know NOTHING about it I think the best way to answer is to state that you don't really know but say what you do know. For example, suppose the interviewer asks "What are some strategies for dealing with imbalanced data?" You may not know the answer to this question, but it's not like you know nothing about it! You could say something like, "Hmm... I'm not familiar with techniques for dealing with imbalanced data, but I do know that when you're data is extremely imbalanced, accuracy isn't super useful. You might want to focus more on metrics which are a bit more robust to imbalanced data like F-measure, AUC, or precision."
-   Don't be afraid to ask for more information, especially when you are being asked an open-ended question! Remember, they are trying to evaluate whether you'll be good at your job. An important part of any job is asking good questions and obtaining the appropriate information necessary to solve a problem. In fact, some questions are purposely vague to see if you can properly scope a problem and obtain the information you need to solve it.
-   Practice thinking through problems out loud. Employers are really interested in seeing how you think through problems. Even if you don't know the answer, talk through your thoughts as you grappling with it.
-   That said, don't be afraid of a little silence. It is OK to take some time to think things through.