---
title: Syllabus
format: 
  html: default
  pdf: default
---

## Course info

### Class meetings & Office Hours

|             |                             |                     |
|----------------------------|-----------------------------|---------------------------------|
| **Lecture** | MWF 3:00 - 3:50pm | Cruzen-Murray Library (CML) 208 |
| **(Optional) Homework Lab** | W 4:00 - 4:50pm (Tentative) | Cruzen-Murray Library (CML) 208 |
| **Office Hours** | M 9:30 - 10:30am | Boone 126B |
| **Office Hours** | T 9:00 - 10:00am | Boone 126B |
| **Office Hours** | W 1:30 - 2:30pm | Boone 126B |
| **Office Hours** | TH 10:00 - 11:00am | Boone 126B |

Office hours are also available by appointment, just email me!


### Instructor Information

-   **Instructor**: Dr. Eric Friedlander
-   **Office**: Boone 126B
-   **Email**: <efriedlander@collegeofidaho.edu>

## Course Learning Objectives

By the end of the semester, you will be able to...

-   tackle predictive modeling problems arising from real data.

-   use Python to fit and evaluate machine learning models.

-   assess whether a proposed model is appropriate and describe its limitations.

-   use Quarto to write reproducible reports and GitHub for version control and collaboration.

-   effectively communicate results results through writing and oral presentations.

## Course community

### College of Idaho Honor Code

> The College of Idaho maintains that academic honesty and integrity are essential values in the educational process. Operating under an Honor Code philosophy, the College expects conduct rooted in honesty, integrity, and understanding, allowing members of a diverse student body to live together and interact and learn from one another in ways that protect both personal freedom and community standards. Violations of academic honesty are addressed primarily by the instructor and may be referred to the [Student Judicial Board](https://collegeofidaho.smartcatalogiq.com/en/current/Undergraduate-Catalog/Policies-and-Procedures/Academic-Misconduct).

By participating in this course, you are agreeing that all your work and conduct will be in accordance with the College of Idaho Honor Code.

### Disability Accommodation Statement

The College of Idaho seeks to provide an educational environment that is accessible to the needs of students with disabilities. The College provides reasonable services to enrolled students who have a documented permanent or temporary physical, psychological, learning, intellectual, or sensory disability that qualifies the student for accommodations under the Americans with Disabilities Act or section 504 of the Rehabilitation Act of 1973. If you have, or think you may have, a disability that impacts your performance as a student in this class, you are encouraged to arrange support services and/or accommodations through the Department of Accessibility and Learning Excellence located in McCain 201B and available via email at <accessibility@collegeofidaho.edu>. Reasonable academic accommodations may be provided to students who submit appropriate and current documentation of their disability. Accommodations can be arranged only through this process and are not retroactively applied. More information can be found on the DALE webpage (<https://www.collegeofidaho.edu/accessibility>).


### Communication

All lecture notes, assignment instructions, an up-to-date schedule, and other course materials may be found on the course website.

Periodic announcements will be sent via email and will also be available through Canvas and grades will be stored in the Canvas gradebook. Please check your email regularly to ensure you have the latest announcements for the course.

### In class agreements

If we discuss/agree to something in class or office hours which requires action from me (e.g. “you may turn in your homework late due to a sporting event”), you MUST send me a follow-up message. If you don’t, I will almost certainly forget, and our agreement will be considered null and void.

### Getting help in the course

-   If you have a question during lecture or lab, feel free to ask it! There are likely other students with the same question, so by asking you will create a learning opportunity for everyone.
-   I am here to help you be successful in the course. You are encouraged to attend *office hours*  and the *homework lab* to ask questions about the course content and assignments. Many questions are most effectively answered as you discuss them with others, so office hours are a valuable resource. You are encouraged to use them!
-   Outside of class and office hours, any general questions about course content or assignments can be emailed to me.

### Email

If you have questions about assignment extensions or accommodations, please email <efriedlander@collegeofidaho.edu>. Please see [Late work policy] for more information. **If you email me about an error please include a screenshot of the error and the code causing the error.** Barring extenuating circumstances, I will respond to course emails within 48 hours Monday - Friday. Response time may be slower for emails sent Friday evening - Sunday.

Check out the [Support](support.qmd) page for more resources.

## Textbook

The official textbook for this course is:

-   An Introduction to Statistical Learning with Applications in Python by Gareth James, Daniela Witten, Trevor Hastie, Robert Tibshirani, and Jonathan Taylor.

    -   Colloquially referred to as "ISLP".
    
    -   It's free!

## Assignments

You will be assessed based on five components: homework, job applications, job interviews, a hack-a-thon, and project.

### Homework

In homework, you will apply what you've learned during lecture to complete data analysis tasks. Homework will completed in teams of three, must be typed up using Quarto, and submitted as .qmd and .pdf files in via GitHub.

### Job Applications & Job Interviews

During this course you will apply to two "jobs". I will generate the job advertisements including real companies and base the job description on the course content and similar job advertisements that I get from online or professional collaborators. Each job application will have three components:

1. A cover letter.
2. A resume.
3. A portfolio.

All three of these should be tailored to the job description and the company to which you are applying. Your portfolio will consist of self-contained data analyses of your choosing. The most straight forward method of creating th to repurpose your homeworks, converting them from a format in which you are responding to exercises to something where you are telling a narrative and demonstrating that you meet the job criteria. To create your portfolio, you will be required to create a website. More details on this will be given during the semester, however the idea of this project is that you will be able to use the things you general when you are applying for jobs.

After you submit your job applications, you will be invited to schedule a one-hour long job interview. **It is your job to schedule your job interview with Dr. Friedlander.** Each job interview will have three portions. The first, lasting 10-15 minutes, will include typical questions that apply to almost any job interview (e.g. "What are your biggest strengths and weaknesses"). The second, lasting 20-30 minutes, will include questions about the portfolio you submitted and your understanding of the required skills described in the job advertising. The third section will mimic what is called a "case interview". Case interviews are extremely common for many jobs, especially those requiring quantitative or computational skills, and can be intimidating. During the case interview portion, you will be presented with a "case study" and asked questions on how you would go about approaching it. The cases themselves will be designed so that they can be solved using the content from class. The goal of this whole exercise is to assess your knowledge of the course content in a way that is authentic while also preparing you to get a job.

### Hack-a-thon

At some point in the semester we will participate in a  "Hack-a-thon" as a class. Namely, you will be given a short period of time (1-3 days) to build a model and make a set of predictions. After the competition is over, you will be required to present on your model. Part of your score will be determine by how well your model performs and extra credit will be given to the top scoring individuals.

### Project

During the latter portion of the course, you will complete a final project that involves a deep exploration of a problem. More details for the final project will be provided later in the course.

## Grading

The final course grade will be calculated as follows:

<center>

| Category                   | Percentage |
|----------------------------|------------|
| Homework                   | 10%        |
| Job Application 1          | 15%        |
| Job Interview 1            | 15%        |
| Job Interview 2            | 20%        |
| Hack-a-thon + Report       | 25%        |
| Project                    | 15%        |


</center>

<br>

The final letter grade will be determined based on the following thresholds:

<center>

| Letter Grade | Final Course Grade |
|--------------|--------------------|
| A            | \>= 93             |
| A-           | 90 - 92.99         |
| B+           | 87 - 89.99         |
| B            | 83 - 86.99         |
| B-           | 80 - 82.99         |
| C+           | 77 - 79.99         |
| C            | 73 - 76.99         |
| C-           | 70 - 72.99         |
| D+           | 67 - 69.99         |
| D            | 63 - 66.99         |
| D-           | 60 - 62.99         |
| F            | \< 60              |

</center>


## Course policies

### Academic honesty

**TL;DR: Don't cheat!**

-   The job application assignments must be completed individually but you are welcome to discuss the assignment with classmates (e.g., discuss what's the best way for approaching a problem, what functions are useful for accomplishing a particular task, etc.). However you may not directly share (i.e. via copy/paste or copying) any code or prose with anyone other than myself.

-   For the hack-a-thon, everyone will submit their predictions and give their own presentations. However, you are encouraged to work together. You are allowed to share code with one another. However, everyone should be able to explain what they did and everyone's projects should be unique in some way. Point reductions will be given if two individuals submit the exact same predictions.

-   For the projects, collaboration within teams is not only allowed, but expected. Communication between teams at a high level is also allowed however you may not share code or components of the project across teams.

-   **Reusing code**: Unless explicitly stated otherwise, you may make use of online resources (e.g. StackOverflow) for coding examples on assignments. If you directly use code from an outside source (or use it as inspiration), you must explicitly cite where you obtained the code. Any recycled code that is discovered and is not explicitly cited will be treated as plagiarism.

-   **Use of artificial intelligence (AI)**: You should treat AI tools, such as ChatGPT, the same as other online resources. There are two guiding principles that govern how you can use AI in this course:[^1] (1) *Cognitive dimension:* Working with AI should not reduce your ability to think clearly. We will practice using AI to facilitate---rather than hinder---learning. (2) *Ethical dimension***:** Students using AI should be transparent about their use and make sure it aligns with academic integrity. In general if the following two things are not true, you are cheating:

    -   You understand and can explain all of the code you have written down or you don't and you have cited the source of that code.
    
    -   All of your prose and narrative were written by yourself.


[^1]: These guiding principles are based on [*Course Policies related to ChatGPT and other AI Tools*](https://docs.google.com/document/d/1WpCeTyiWCPQ9MNCsFeKMDQLSTsg1oKfNIH6MzoSFXqQ/preview) developed by Joel Gladd, Ph.D.[↩︎](https://sta101-f23.github.io/course-syllabus.html#fnref1)

If you are unsure if the use of a particular resource complies with the academic honesty policy, just ask.

Regardless of course delivery format, it is the responsibility of all students to understand and follow all College of Idaho policies, including academic integrity (e.g., completing one's own work, following proper citation of sources, adhering to guidance around group work projects, and more). Ignoring these requirements is a violation of the Honor Code.

### Late work policy

The due dates for assignments are there to help you keep up with the course material and to ensure the teaching team can provide feedback within a timely manner. I understand that things come up periodically that could make it difficult to submit an assignment by the deadline.

-   **Late Homework:** Homework is completion based and well be accepted without penalty for a week. However, if your homework is turned in after I begin grading it, you will not receive any feedback.

-   **School-Sponsored Events/Illness:** If an assignment or meeting must be missed due to a school-sponsored event, you must let me know at least a week ahead of time so that we can schedule a time for you to make up the work before you leave. If an assignment or meeting must be missed due to illness, you must let me know as soon as it is safe for you to do so and before the assignment or meeting if possible. Failure to adhere to this policy will result in a 35% penalty on the corresponding assignment.
