{
  "hash": "5ecdd6a774fbf3f5f2a11a41513fcc08",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: 'Math 4025: Multiple Linear Regression + Data Splitting'\n---\n\n\n## Computational Setup\n\n::: {#37b4f912 .cell execution_count=1}\n``` {.python .cell-code}\nimport pandas as pd\nimport numpy as np\nfrom sklearn.linear_model import LinearRegression\nimport matplotlib.pyplot as plt\nimport seaborn as sns\nfrom itables import show\n```\n:::\n\n\n## [Question!!!]{style=\"color:blue\"}\n\nAs a model's flexibility increases:\n\n::: panel-tabset\n\n## Questions\n\n1. its variance (increases/decreases)\n2. its bias  (increases/decreases)\n3. its training MSE  (increases/decreases)\n4. its test MSE  (describe)\n\n## Answers\n1. its variance  (**increases**)\n2. its bias  (**decreases**)\n3. its training MSE  (**decreases**)\n4. its test MSE  (**decreases at first, then increases and the model starts to overfit, U-shaped**)\n\n:::\n\n\n\n<!-- ## Bias-Variance Trade-Off App {.smaller} -->\n\n<!-- When Dr. F tell you, navigate to [this app](https://efriedlander.shinyapps.io/BVTappRegression/) -->\n\n<!-- -   Select your assigned data set and look at the second row of plots -->\n<!--   +   Which order polynomials have the lowest Bias, Variance, training MSE, and test MSE -->\n<!--       +   Which order polynomial would you say is best? -->\n<!--   +   Scroll down to the last row of plots and discuss how these images support your answers -->\n<!--   +   Repeat this process for different amounts of noise? -->\n<!--   +   Return to the first row of plots and select three different order polynomials based on your answers above... is the bias variance trade-off visible in this plot? -->\n\n\n# Modeling in Python\n\n## Outlet Data {.smaller} \n\nSuppose the CEO of a restaurant franchise is considering opening new outlets in different cities. They would like to expand their business to cities that give them higher profits with the assumption that highly populated cities will probably yield higher profits.\n\nThey have data on the population (in 100,000) and profit (in $1,000) at 97 cities where they currently have outlets.\n\n::: {#445276f3 .cell execution_count=2}\n``` {.python .cell-code}\noutlets = pd.read_csv(\"../data/outlets.csv\")\nshow(outlets.head())  # first six observations of the dataset\n```\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<!--| quarto-html-table-processing: none -->\n<table id=\"itables_2b48f82a_299a_44e7_84a5_bc9d99ddfed0\"><tbody><tr>\n    <td style=\"vertical-align:middle; text-align:left\">\n    <a href=https://mwouts.github.io/itables/><svg class=\"main-svg\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\"\nwidth=\"64\" viewBox=\"0 0 500 400\" style=\"font-family: 'Droid Sans', sans-serif;\">\n    <g style=\"fill:#d9d7fc\">\n        <path d=\"M100,400H500V357H100Z\" />\n        <path d=\"M100,300H400V257H100Z\" />\n        <path d=\"M0,200H400V157H0Z\" />\n        <path d=\"M100,100H500V57H100Z\" />\n        <path d=\"M100,350H500V307H100Z\" />\n        <path d=\"M100,250H400V207H100Z\" />\n        <path d=\"M0,150H400V107H0Z\" />\n        <path d=\"M100,50H500V7H100Z\" />\n    </g>\n    <g style=\"fill:#1a1366;stroke:#1a1366;\">\n   <rect x=\"100\" y=\"7\" width=\"400\" height=\"43\">\n    <animate\n      attributeName=\"width\"\n      values=\"0;400;0\"\n      dur=\"5s\"\n      repeatCount=\"indefinite\" />\n      <animate\n      attributeName=\"x\"\n      values=\"100;100;500\"\n      dur=\"5s\"\n      repeatCount=\"indefinite\" />\n  </rect>\n        <rect x=\"0\" y=\"107\" width=\"400\" height=\"43\">\n    <animate\n      attributeName=\"width\"\n      values=\"0;400;0\"\n      dur=\"3.5s\"\n      repeatCount=\"indefinite\" />\n    <animate\n      attributeName=\"x\"\n      values=\"0;0;400\"\n      dur=\"3.5s\"\n      repeatCount=\"indefinite\" />\n  </rect>\n        <rect x=\"100\" y=\"207\" width=\"300\" height=\"43\">\n    <animate\n      attributeName=\"width\"\n      values=\"0;300;0\"\n      dur=\"3s\"\n      repeatCount=\"indefinite\" />\n    <animate\n      attributeName=\"x\"\n      values=\"100;100;400\"\n      dur=\"3s\"\n      repeatCount=\"indefinite\" />\n  </rect>\n        <rect x=\"100\" y=\"307\" width=\"400\" height=\"43\">\n    <animate\n      attributeName=\"width\"\n      values=\"0;400;0\"\n      dur=\"4s\"\n      repeatCount=\"indefinite\" />\n      <animate\n      attributeName=\"x\"\n      values=\"100;100;500\"\n      dur=\"4s\"\n      repeatCount=\"indefinite\" />\n  </rect>\n        <g style=\"fill:transparent;stroke-width:8; stroke-linejoin:round\" rx=\"5\">\n            <g transform=\"translate(45 50) rotate(-45)\">\n                <circle r=\"33\" cx=\"0\" cy=\"0\" />\n                <rect x=\"-8\" y=\"32\" width=\"16\" height=\"30\" />\n            </g>\n\n            <g transform=\"translate(450 152)\">\n                <polyline points=\"-15,-20 -35,-20 -35,40 25,40 25,20\" />\n                <rect x=\"-15\" y=\"-40\" width=\"60\" height=\"60\" />\n            </g>\n\n            <g transform=\"translate(50 352)\">\n                <polygon points=\"-35,-5 0,-40 35,-5\" />\n                <polygon points=\"-35,10 0,45 35,10\" />\n            </g>\n\n            <g transform=\"translate(75 250)\">\n                <polyline points=\"-30,30 -60,0 -30,-30\" />\n                <polyline points=\"0,30 -30,0 0,-30\" />\n            </g>\n\n            <g transform=\"translate(425 250) rotate(180)\">\n                <polyline points=\"-30,30 -60,0 -30,-30\" />\n                <polyline points=\"0,30 -30,0 0,-30\" />\n            </g>\n        </g>\n    </g>\n</svg>\n</a>\n    Loading ITables v2.6.2 from the internet...\n    (need <a href=https://mwouts.github.io/itables/troubleshooting.html>help</a>?)</td>\n    </tr></tbody></table>\n<link href=\"https://www.unpkg.com/dt_for_itables@2.4.0/dt_bundle.css\" rel=\"stylesheet\">\n<script type=\"module\">\n    import { ITable, jQuery as $ } from 'https://www.unpkg.com/dt_for_itables@2.4.0/dt_bundle.js';\n\n    document.querySelectorAll(\"#itables_2b48f82a_299a_44e7_84a5_bc9d99ddfed0:not(.dataTable)\").forEach(table => {\n        if (!(table instanceof HTMLTableElement))\n            return;\n\n        let dt_args = {\"layout\": {\"topStart\": null, \"topEnd\": null, \"bottomStart\": null, \"bottomEnd\": null}, \"text_in_header_can_be_selected\": true, \"classes\": [\"display\", \"nowrap\"], \"order\": [], \"style\": {\"table-layout\": \"auto\", \"width\": \"auto\", \"margin\": \"auto\", \"caption-side\": \"bottom\"}, \"table_html\": \"<table><thead>\\n    <tr style=\\\"text-align: right;\\\">\\n      \\n      <th>population</th>\\n      <th>profit</th>\\n    </tr>\\n  </thead></table>\", \"data_json\": \"[[6.1101, 17.592], [5.5277, 9.1302], [8.5186, 13.662], [7.0032, 11.854], [5.8598, 6.8233]]\"};\n        new ITable(table, dt_args);\n    });\n</script>\n```\n:::\n:::\n\n\n## Python as an open-source language\n\n- Python is an open source language\n  + Advantages:\n    + Packages for almost anything you want\n    + \"Cutting edge\" methods rolled out quickly and early\n  + Disadvantages\n    + Many packages (especially new ones) may have bugs\n    + Lots of syntactical diversity\n    + Syntax is frequently dependent on the needs of the person who wrote the package and conventions at the time the package was created\n    \n## Enter `pandas` and `plotnine`\n\n> pandas is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool.\n\n> plotnine is an implementation of a grammar of graphics in Python based on ggplot2.\n\n- `pandas` is for manipulating data\n- `plotnine` is for visualizing data (similar to ggplot2)\n\n## Enter `scikit-learn`\n\n> Scikit-learn is a simple and efficient tools for predictive data analysis built on NumPy, SciPy, and matplotlib.\n\n- `scikit-learn` (often imported as `sklearn`) provides a unified framework for building machine learning models in Python\n- Similar philosophy to `tidymodels` in R: consistent API across different model types\n\n## Back to linear regression\n\n::: {#8ebe0659 .cell execution_count=3}\n``` {.python .cell-code}\nfrom plotnine import ggplot, aes, geom_point, geom_smooth\n\n(\n    ggplot(outlets, aes(x=\"population\", y=\"profit\"))\n    + geom_point()  # create scatterplot\n    + geom_smooth(method=\"lm\", se=False)  # add the regression line\n)\n```\n\n::: {.cell-output .cell-output-display execution_count=3}\n![](04-MultipleRegression_files/figure-revealjs/cell-4-output-1.png){width=960 height=480}\n:::\n:::\n\n\n## Classic Linear Regression in Python {.smaller}\n\n::::{.columns}\n:::{.column}\n\n::: {#e54aa8b8 .cell execution_count=4}\n``` {.python .cell-code}\nimport statsmodels.formula.api as smf\n\noutlets_model = smf.ols(\"profit ~ population\", data=outlets).fit()\nprint(outlets_model.params)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nIntercept    -3.895781\npopulation    1.193034\ndtype: float64\n```\n:::\n:::\n\n\n:::\n\n:::{.column}\n\nThis corresponds to the model:\n\n$$\n\\begin{aligned}\n\\text{Profit}  &= -3.90 + 1.19\\times\\text{Population}\\\\\n\\hat{Y}_i &= -3.90 + 1.19X_i\n\\end{aligned}\n$$\ni.e. $\\hat{\\beta}_0 = -3.90$ and $\\hat{\\beta}_1 = 1.19$\n:::\n::::\n\n## Modeling with `scikit-learn`\n\n1. Import the model class (e.g. `LinearRegression`, `LogisticRegression`)\n\n2. Instantiate the model with desired hyperparameters\n\n3. Fit the model to data using `.fit(X, y)`\n\n4. Make predictions using `.predict(X_new)`\n\n## Linear Regression with `scikit-learn`\n\n::: {#96d44846 .cell execution_count=5}\n``` {.python .cell-code code-line-numbers=\"|2|5|8|11\"}\n# Import the model class\nfrom sklearn.linear_model import LinearRegression\n\n# Instantiate the model\nlm_model = LinearRegression()\n\n# Prepare the data (scikit-learn expects 2D arrays for X)\nX = outlets[[\"population\"]]  # double brackets to keep as DataFrame\ny = outlets[\"profit\"]\n\n# Fit the model\nlm_model_fit = lm_model.fit(X, y)\n```\n:::\n\n\n## Linear Regression with `scikit-learn`\n\n::: {#758acdb3 .cell execution_count=6}\n``` {.python .cell-code}\n# Display the coefficients\nprint(f\"Intercept: {lm_model_fit.intercept_:.4f}\")\nprint(f\"Coefficient for population: {lm_model_fit.coef_[0]:.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nIntercept: -3.8958\nCoefficient for population: 1.1930\n```\n:::\n:::\n\n\nSame model as before:\n\n$$\n\\begin{aligned}\n\\text{Profit}  &= -3.90 + 1.19\\times\\text{Population}\\\\\n\\hat{Y}_i &= -3.90 + 1.19X_i\n\\end{aligned}\n$$\n\n\n\n## Linear Regression in Python: Prediction\n\n::: {#e224ca06 .cell execution_count=7}\n``` {.python .cell-code}\n# Generate new data\nnp.random.seed(42)\nnew_cities = pd.DataFrame({\"population\": np.random.normal(7, 3, 100)})\n\n# Make predictions\npredictions = lm_model_fit.predict(new_cities[[\"population\"]])\nnew_cities[\"predicted_profit\"] = predictions\n\nshow(new_cities.head(10))\n```\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<!--| quarto-html-table-processing: none -->\n<table id=\"itables_a5f157a4_c73d_4c5e_8841_f1d563b01ac9\"><tbody><tr>\n    <td style=\"vertical-align:middle; text-align:left\">\n    <a href=https://mwouts.github.io/itables/><svg class=\"main-svg\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\"\nwidth=\"64\" viewBox=\"0 0 500 400\" style=\"font-family: 'Droid Sans', sans-serif;\">\n    <g style=\"fill:#d9d7fc\">\n        <path d=\"M100,400H500V357H100Z\" />\n        <path d=\"M100,300H400V257H100Z\" />\n        <path d=\"M0,200H400V157H0Z\" />\n        <path d=\"M100,100H500V57H100Z\" />\n        <path d=\"M100,350H500V307H100Z\" />\n        <path d=\"M100,250H400V207H100Z\" />\n        <path d=\"M0,150H400V107H0Z\" />\n        <path d=\"M100,50H500V7H100Z\" />\n    </g>\n    <g style=\"fill:#1a1366;stroke:#1a1366;\">\n   <rect x=\"100\" y=\"7\" width=\"400\" height=\"43\">\n    <animate\n      attributeName=\"width\"\n      values=\"0;400;0\"\n      dur=\"5s\"\n      repeatCount=\"indefinite\" />\n      <animate\n      attributeName=\"x\"\n      values=\"100;100;500\"\n      dur=\"5s\"\n      repeatCount=\"indefinite\" />\n  </rect>\n        <rect x=\"0\" y=\"107\" width=\"400\" height=\"43\">\n    <animate\n      attributeName=\"width\"\n      values=\"0;400;0\"\n      dur=\"3.5s\"\n      repeatCount=\"indefinite\" />\n    <animate\n      attributeName=\"x\"\n      values=\"0;0;400\"\n      dur=\"3.5s\"\n      repeatCount=\"indefinite\" />\n  </rect>\n        <rect x=\"100\" y=\"207\" width=\"300\" height=\"43\">\n    <animate\n      attributeName=\"width\"\n      values=\"0;300;0\"\n      dur=\"3s\"\n      repeatCount=\"indefinite\" />\n    <animate\n      attributeName=\"x\"\n      values=\"100;100;400\"\n      dur=\"3s\"\n      repeatCount=\"indefinite\" />\n  </rect>\n        <rect x=\"100\" y=\"307\" width=\"400\" height=\"43\">\n    <animate\n      attributeName=\"width\"\n      values=\"0;400;0\"\n      dur=\"4s\"\n      repeatCount=\"indefinite\" />\n      <animate\n      attributeName=\"x\"\n      values=\"100;100;500\"\n      dur=\"4s\"\n      repeatCount=\"indefinite\" />\n  </rect>\n        <g style=\"fill:transparent;stroke-width:8; stroke-linejoin:round\" rx=\"5\">\n            <g transform=\"translate(45 50) rotate(-45)\">\n                <circle r=\"33\" cx=\"0\" cy=\"0\" />\n                <rect x=\"-8\" y=\"32\" width=\"16\" height=\"30\" />\n            </g>\n\n            <g transform=\"translate(450 152)\">\n                <polyline points=\"-15,-20 -35,-20 -35,40 25,40 25,20\" />\n                <rect x=\"-15\" y=\"-40\" width=\"60\" height=\"60\" />\n            </g>\n\n            <g transform=\"translate(50 352)\">\n                <polygon points=\"-35,-5 0,-40 35,-5\" />\n                <polygon points=\"-35,10 0,45 35,10\" />\n            </g>\n\n            <g transform=\"translate(75 250)\">\n                <polyline points=\"-30,30 -60,0 -30,-30\" />\n                <polyline points=\"0,30 -30,0 0,-30\" />\n            </g>\n\n            <g transform=\"translate(425 250) rotate(180)\">\n                <polyline points=\"-30,30 -60,0 -30,-30\" />\n                <polyline points=\"0,30 -30,0 0,-30\" />\n            </g>\n        </g>\n    </g>\n</svg>\n</a>\n    Loading ITables v2.6.2 from the internet...\n    (need <a href=https://mwouts.github.io/itables/troubleshooting.html>help</a>?)</td>\n    </tr></tbody></table>\n<link href=\"https://www.unpkg.com/dt_for_itables@2.4.0/dt_bundle.css\" rel=\"stylesheet\">\n<script type=\"module\">\n    import { ITable, jQuery as $ } from 'https://www.unpkg.com/dt_for_itables@2.4.0/dt_bundle.js';\n\n    document.querySelectorAll(\"#itables_a5f157a4_c73d_4c5e_8841_f1d563b01ac9:not(.dataTable)\").forEach(table => {\n        if (!(table instanceof HTMLTableElement))\n            return;\n\n        let dt_args = {\"layout\": {\"topStart\": null, \"topEnd\": null, \"bottomStart\": null, \"bottomEnd\": null}, \"text_in_header_can_be_selected\": true, \"classes\": [\"display\", \"nowrap\"], \"order\": [], \"style\": {\"table-layout\": \"auto\", \"width\": \"auto\", \"margin\": \"auto\", \"caption-side\": \"bottom\"}, \"table_html\": \"<table><thead>\\n    <tr style=\\\"text-align: right;\\\">\\n      \\n      <th>population</th>\\n      <th>predicted_profit</th>\\n    </tr>\\n  </thead></table>\", \"data_json\": \"[[8.490142, 6.233245], [6.585207, 3.960593], [8.943066, 6.773597], [11.56909, 9.906532], [6.29754, 3.617396], [6.297589, 3.617455], [11.737638, 10.107617], [9.302304, 7.202181], [5.591577, 2.775158], [8.62768, 6.397332]]\"};\n        new ITable(table, dt_args);\n    });\n</script>\n```\n:::\n:::\n\n\nNote: New data must be a DataFrame with the same column names as the training data\n\n\n# Multiple Linear Regression\n\n## Multiple Linear Regression\n\n- Response: $Y$\n- Predictor Variables: $X_1, X_2, \\ldots, X_p$\n- Assume true relationship:\n\n$$\n\\begin{aligned}\nY&=f(\\mathbf{X}) + \\epsilon\\\\\n&=\\beta_0 + \\beta_1 X_1 + \\beta_2 X_2 + \\ldots + \\beta_p X_p + \\epsilon\n\\end{aligned}\n$$\nwhere $\\beta_j$ quantifies the association between the $j^{th}$ predictor and the response.\n\n\n\n## [Multiple Linear Regression: Estimating Parameters]{.r-fit-text} {.smaller}\n\n- Suppose $\\hat{\\beta}_0, \\hat{\\beta}_1, \\ldots, \\hat{\\beta}_p$ are estimates of $\\beta_0, \\beta_1, \\ldots, \\beta_p$\n- Training Data:\n  + Observed response: $y_i$ for $i=1,\\ldots,n$\n  + Observed predictors: $x_{1i}, x_{2i}, \\ldots x_{pi}$ for $i=1,\\ldots, n$\n- Predicted response: \n$$\\hat{y}_i = \\hat{\\beta}_0 + \\hat{\\beta}_1x_{1i} + \\ldots + \\hat{\\beta}_px_{pi} \\text{ for } i=1, \\ldots, n$$\n- Residuals: $e_i = \\hat{y}_i - y_i$ for $i=1, \\ldots, n$\n- Mean Squared Error (MSE): $MSE =\\dfrac{e^2_1+e^2_2+\\ldots+e^2_n}{n}$\n\n## [Multiple Linear Regression: Estimating Parameters]{.r-fit-text}\n\n- **Goal:** Use *training data* to find $\\hat{\\beta}_0, \\hat{\\beta}_1, \\ldots, \\hat{\\beta}_p$ that minimizes MSE\n  + $\\hat{\\beta}_i$'s called **least-squares estimators**\n  + Since minimizing MSE $\\implies$ MSE is called **cost/loss function**\n- Can use calculus or gradient descent to find $\\hat{\\beta}_i$'s\n\n\n\n## House Prices dataset {.smaller}\n\n- `size` is in square feet\n- `num_bedrooms` is a count\n- `price` is in $1,000's\n\n::: {#5ced9203 .cell execution_count=8}\n``` {.python .cell-code}\nhouse_prices = pd.read_csv(\"../data/house_prices.csv\")\nshow(house_prices.head(6))  # print first 6 observations\n```\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<!--| quarto-html-table-processing: none -->\n<table id=\"itables_eced40b6_32f5_4315_b563_629d29000cc7\"><tbody><tr>\n    <td style=\"vertical-align:middle; text-align:left\">\n    <a href=https://mwouts.github.io/itables/><svg class=\"main-svg\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\"\nwidth=\"64\" viewBox=\"0 0 500 400\" style=\"font-family: 'Droid Sans', sans-serif;\">\n    <g style=\"fill:#d9d7fc\">\n        <path d=\"M100,400H500V357H100Z\" />\n        <path d=\"M100,300H400V257H100Z\" />\n        <path d=\"M0,200H400V157H0Z\" />\n        <path d=\"M100,100H500V57H100Z\" />\n        <path d=\"M100,350H500V307H100Z\" />\n        <path d=\"M100,250H400V207H100Z\" />\n        <path d=\"M0,150H400V107H0Z\" />\n        <path d=\"M100,50H500V7H100Z\" />\n    </g>\n    <g style=\"fill:#1a1366;stroke:#1a1366;\">\n   <rect x=\"100\" y=\"7\" width=\"400\" height=\"43\">\n    <animate\n      attributeName=\"width\"\n      values=\"0;400;0\"\n      dur=\"5s\"\n      repeatCount=\"indefinite\" />\n      <animate\n      attributeName=\"x\"\n      values=\"100;100;500\"\n      dur=\"5s\"\n      repeatCount=\"indefinite\" />\n  </rect>\n        <rect x=\"0\" y=\"107\" width=\"400\" height=\"43\">\n    <animate\n      attributeName=\"width\"\n      values=\"0;400;0\"\n      dur=\"3.5s\"\n      repeatCount=\"indefinite\" />\n    <animate\n      attributeName=\"x\"\n      values=\"0;0;400\"\n      dur=\"3.5s\"\n      repeatCount=\"indefinite\" />\n  </rect>\n        <rect x=\"100\" y=\"207\" width=\"300\" height=\"43\">\n    <animate\n      attributeName=\"width\"\n      values=\"0;300;0\"\n      dur=\"3s\"\n      repeatCount=\"indefinite\" />\n    <animate\n      attributeName=\"x\"\n      values=\"100;100;400\"\n      dur=\"3s\"\n      repeatCount=\"indefinite\" />\n  </rect>\n        <rect x=\"100\" y=\"307\" width=\"400\" height=\"43\">\n    <animate\n      attributeName=\"width\"\n      values=\"0;400;0\"\n      dur=\"4s\"\n      repeatCount=\"indefinite\" />\n      <animate\n      attributeName=\"x\"\n      values=\"100;100;500\"\n      dur=\"4s\"\n      repeatCount=\"indefinite\" />\n  </rect>\n        <g style=\"fill:transparent;stroke-width:8; stroke-linejoin:round\" rx=\"5\">\n            <g transform=\"translate(45 50) rotate(-45)\">\n                <circle r=\"33\" cx=\"0\" cy=\"0\" />\n                <rect x=\"-8\" y=\"32\" width=\"16\" height=\"30\" />\n            </g>\n\n            <g transform=\"translate(450 152)\">\n                <polyline points=\"-15,-20 -35,-20 -35,40 25,40 25,20\" />\n                <rect x=\"-15\" y=\"-40\" width=\"60\" height=\"60\" />\n            </g>\n\n            <g transform=\"translate(50 352)\">\n                <polygon points=\"-35,-5 0,-40 35,-5\" />\n                <polygon points=\"-35,10 0,45 35,10\" />\n            </g>\n\n            <g transform=\"translate(75 250)\">\n                <polyline points=\"-30,30 -60,0 -30,-30\" />\n                <polyline points=\"0,30 -30,0 0,-30\" />\n            </g>\n\n            <g transform=\"translate(425 250) rotate(180)\">\n                <polyline points=\"-30,30 -60,0 -30,-30\" />\n                <polyline points=\"0,30 -30,0 0,-30\" />\n            </g>\n        </g>\n    </g>\n</svg>\n</a>\n    Loading ITables v2.6.2 from the internet...\n    (need <a href=https://mwouts.github.io/itables/troubleshooting.html>help</a>?)</td>\n    </tr></tbody></table>\n<link href=\"https://www.unpkg.com/dt_for_itables@2.4.0/dt_bundle.css\" rel=\"stylesheet\">\n<script type=\"module\">\n    import { ITable, jQuery as $ } from 'https://www.unpkg.com/dt_for_itables@2.4.0/dt_bundle.js';\n\n    document.querySelectorAll(\"#itables_eced40b6_32f5_4315_b563_629d29000cc7:not(.dataTable)\").forEach(table => {\n        if (!(table instanceof HTMLTableElement))\n            return;\n\n        let dt_args = {\"layout\": {\"topStart\": null, \"topEnd\": null, \"bottomStart\": null, \"bottomEnd\": null}, \"text_in_header_can_be_selected\": true, \"classes\": [\"display\", \"nowrap\"], \"order\": [], \"style\": {\"table-layout\": \"auto\", \"width\": \"auto\", \"margin\": \"auto\", \"caption-side\": \"bottom\"}, \"table_html\": \"<table><thead>\\n    <tr style=\\\"text-align: right;\\\">\\n      \\n      <th>size</th>\\n      <th>num_bedrooms</th>\\n      <th>price</th>\\n    </tr>\\n  </thead></table>\", \"data_json\": \"[[2104, 3, 399.9], [1600, 3, 329.9], [2400, 3, 369.0], [1416, 2, 232.0], [3000, 4, 539.9], [1985, 4, 299.9]]\"};\n        new ITable(table, dt_args);\n    });\n</script>\n```\n:::\n:::\n\n\n## Multiple Linear Regression\n\nSome Exploratory Data Analysis (EDA)\n\n::: {#f66ecf2a .cell execution_count=9}\n``` {.python .cell-code}\n# Correlation plot using seaborn\nsns.pairplot(house_prices)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](04-MultipleRegression_files/figure-revealjs/cell-10-output-1.png){width=710 height=709}\n:::\n:::\n\n\n## Multiple Linear Regression in Python {.smaller}\n\n::: {#660c75af .cell execution_count=10}\n``` {.python .cell-code}\n# Prepare the data\nX_house = house_prices[[\"size\", \"num_bedrooms\"]]\ny_house = house_prices[\"price\"]\n\n# Fit the model\nmlr_model = LinearRegression()\nhouse_price_mlr = mlr_model.fit(X_house, y_house)\n\n# Display coefficients\ncoef_df = pd.DataFrame({\n    \"term\": [\"Intercept\", \"size\", \"num_bedrooms\"],\n    \"estimate\": [house_price_mlr.intercept_] + list(house_price_mlr.coef_)\n})\nshow(coef_df)\n```\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<!--| quarto-html-table-processing: none -->\n<table id=\"itables_4f9ae291_8d9d_4450_bc5d_ff92ef854610\"><tbody><tr>\n    <td style=\"vertical-align:middle; text-align:left\">\n    <a href=https://mwouts.github.io/itables/><svg class=\"main-svg\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\"\nwidth=\"64\" viewBox=\"0 0 500 400\" style=\"font-family: 'Droid Sans', sans-serif;\">\n    <g style=\"fill:#d9d7fc\">\n        <path d=\"M100,400H500V357H100Z\" />\n        <path d=\"M100,300H400V257H100Z\" />\n        <path d=\"M0,200H400V157H0Z\" />\n        <path d=\"M100,100H500V57H100Z\" />\n        <path d=\"M100,350H500V307H100Z\" />\n        <path d=\"M100,250H400V207H100Z\" />\n        <path d=\"M0,150H400V107H0Z\" />\n        <path d=\"M100,50H500V7H100Z\" />\n    </g>\n    <g style=\"fill:#1a1366;stroke:#1a1366;\">\n   <rect x=\"100\" y=\"7\" width=\"400\" height=\"43\">\n    <animate\n      attributeName=\"width\"\n      values=\"0;400;0\"\n      dur=\"5s\"\n      repeatCount=\"indefinite\" />\n      <animate\n      attributeName=\"x\"\n      values=\"100;100;500\"\n      dur=\"5s\"\n      repeatCount=\"indefinite\" />\n  </rect>\n        <rect x=\"0\" y=\"107\" width=\"400\" height=\"43\">\n    <animate\n      attributeName=\"width\"\n      values=\"0;400;0\"\n      dur=\"3.5s\"\n      repeatCount=\"indefinite\" />\n    <animate\n      attributeName=\"x\"\n      values=\"0;0;400\"\n      dur=\"3.5s\"\n      repeatCount=\"indefinite\" />\n  </rect>\n        <rect x=\"100\" y=\"207\" width=\"300\" height=\"43\">\n    <animate\n      attributeName=\"width\"\n      values=\"0;300;0\"\n      dur=\"3s\"\n      repeatCount=\"indefinite\" />\n    <animate\n      attributeName=\"x\"\n      values=\"100;100;400\"\n      dur=\"3s\"\n      repeatCount=\"indefinite\" />\n  </rect>\n        <rect x=\"100\" y=\"307\" width=\"400\" height=\"43\">\n    <animate\n      attributeName=\"width\"\n      values=\"0;400;0\"\n      dur=\"4s\"\n      repeatCount=\"indefinite\" />\n      <animate\n      attributeName=\"x\"\n      values=\"100;100;500\"\n      dur=\"4s\"\n      repeatCount=\"indefinite\" />\n  </rect>\n        <g style=\"fill:transparent;stroke-width:8; stroke-linejoin:round\" rx=\"5\">\n            <g transform=\"translate(45 50) rotate(-45)\">\n                <circle r=\"33\" cx=\"0\" cy=\"0\" />\n                <rect x=\"-8\" y=\"32\" width=\"16\" height=\"30\" />\n            </g>\n\n            <g transform=\"translate(450 152)\">\n                <polyline points=\"-15,-20 -35,-20 -35,40 25,40 25,20\" />\n                <rect x=\"-15\" y=\"-40\" width=\"60\" height=\"60\" />\n            </g>\n\n            <g transform=\"translate(50 352)\">\n                <polygon points=\"-35,-5 0,-40 35,-5\" />\n                <polygon points=\"-35,10 0,45 35,10\" />\n            </g>\n\n            <g transform=\"translate(75 250)\">\n                <polyline points=\"-30,30 -60,0 -30,-30\" />\n                <polyline points=\"0,30 -30,0 0,-30\" />\n            </g>\n\n            <g transform=\"translate(425 250) rotate(180)\">\n                <polyline points=\"-30,30 -60,0 -30,-30\" />\n                <polyline points=\"0,30 -30,0 0,-30\" />\n            </g>\n        </g>\n    </g>\n</svg>\n</a>\n    Loading ITables v2.6.2 from the internet...\n    (need <a href=https://mwouts.github.io/itables/troubleshooting.html>help</a>?)</td>\n    </tr></tbody></table>\n<link href=\"https://www.unpkg.com/dt_for_itables@2.4.0/dt_bundle.css\" rel=\"stylesheet\">\n<script type=\"module\">\n    import { ITable, jQuery as $ } from 'https://www.unpkg.com/dt_for_itables@2.4.0/dt_bundle.js';\n\n    document.querySelectorAll(\"#itables_4f9ae291_8d9d_4450_bc5d_ff92ef854610:not(.dataTable)\").forEach(table => {\n        if (!(table instanceof HTMLTableElement))\n            return;\n\n        let dt_args = {\"layout\": {\"topStart\": null, \"topEnd\": null, \"bottomStart\": null, \"bottomEnd\": null}, \"text_in_header_can_be_selected\": true, \"classes\": [\"display\", \"nowrap\"], \"order\": [], \"style\": {\"table-layout\": \"auto\", \"width\": \"auto\", \"margin\": \"auto\", \"caption-side\": \"bottom\"}, \"table_html\": \"<table><thead>\\n    <tr style=\\\"text-align: right;\\\">\\n      \\n      <th>term</th>\\n      <th>estimate</th>\\n    </tr>\\n  </thead></table>\", \"data_json\": \"[[\\\"Intercept\\\", 89.597766], [\\\"size\\\", 0.139211], [\\\"num_bedrooms\\\", -8.737915]]\"};\n        new ITable(table, dt_args);\n    });\n</script>\n```\n:::\n:::\n\n\n## [Multiple Linear Regression: Interpreting Parameters]{.r-fit-text} {.smaller}\n\n- $\\hat{\\beta}_0=89.5978$: The intercept $\\implies$ a house with 0 square feet and 0 bedrooms would cost approximately \\$89,598.80. Is this meaningful in context? [Not really]{.fragment .fade-in}\n- $\\hat{\\beta}_1=0.1392$: With `num_bedrooms` remaining fixed, an additional 1 square foot of `size` leads to an increase in `price` by approximately \\$139.20.\n- $\\hat{\\beta}_2=-8.7379$: With `size` remaining fixed, an additional bedroom leads to an decrease in `price` of approximately \\$8,737.90.\n\n. . .\n\n- Hmm.... that's a little weird...\n- **Simpson's Paradox:** when relationship between two variables disappears or reverses when controlling for a third, **confounding variable**\n\n## [Multiple Linear Regression: Interpreting Parameters]{.r-fit-text}\n\n:::{.incremental}\n- Write down our model in mathematical notation\n- $\\text{price} = 89.5978 + 0.1392\\times\\text{size} - 8.7379\\times\\text{num\\_bedrooms}$\n- $Y = 89.5978 + 0.1392X_1 - 8.7379X_2$\n:::\n\n\n## Multiple Linear Regression: Prediction {.smaller}\n\n- Prediction of `price` when `size` is 2000 square feet for a house with 3 bedrooms\n- $\\text{sales} = 89.5978 + 0.1392\\times2000 - 8.7379\\times3 = 341.7841$\n\n. . .\n\n::: {#c0557091 .cell execution_count=11}\n``` {.python .cell-code}\n# Make prediction\nnew_house = pd.DataFrame({\"size\": [2000], \"num_bedrooms\": [3]})\nprediction = house_price_mlr.predict(new_house)\nprint(f\"Predicted price: {prediction[0]:.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nPredicted price: 341.8053\n```\n:::\n:::\n\n\n- Why don't these match exactly? [**rounding**]{.fragment .fade-in}\n\n\n## Linear Regression: Comparing Models {.smaller}\n\n:::{.fragment}\n:::{.incremental}\n- Many methods for comparing regression models from your regression course\n- Today: Data splitting\n- First: New Data\n:::\n:::\n:::{.fragment}\n- **ames housing data**\n  + Many variables\n  + Focus on:\n    * `Sale_Price`: in dollars\n    * `Gr_Liv_Area`: size in square feet\n    * `Bedroom_AbvGr`: number of bedrooms above grade\n:::\n\n",
    "supporting": [
      "04-MultipleRegression_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}